apiVersion: v1
kind: Service
metadata:
  name: dummy-upi-service
  namespace: devsecops
  labels:
    app: dummy-upi-app
    app.kubernetes.io/name: dummy-upi-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: autonomous-devsecops-engine
spec:
  type: ClusterIP
  selector:
    app: dummy-upi-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
